// ...existing code...
	protected $routeMiddleware = [
		// ...existing entries...
		'ensure.belongs.to.site' => \App\Http\Middleware\EnsureModelBelongsToSelectedSite::class,
		// ...existing entries...
	];
// ...existing code...

