// ...existing code...
	protected $routeMiddleware = [
		// ...existing entries...
		'ensure.belongs.to.instance' => \App\Http\Middleware\EnsureModelBelongsToSelectedInstance::class,
		// ...existing entries...
	];
// ...existing code...

