// ...existing code...
	protected $middleware = [
		// ...existing code...
	];

	protected $middlewareGroups = [
		'web' => [
			\App\Http\Middleware\DetectSiteByHost::class,
			// ...existing code...
		],
		// ...existing code...
	];

	protected $routeMiddleware = [
		// ...existing entries...
		'ensure.belongs.to.site' => \App\Http\Middleware\EnsureModelBelongsToSelectedSite::class,
		'ensure.admin.host' => \App\Http\Middleware\EnsureAdminHost::class,
		// ...existing entries...
	];
// ...existing code...
